routes/web.php
<?php

Route::get('/r', function ()
{
    function philsroutes()
    {
        $routeCollection = Route::getRoutes();
        echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">';
        echo "<div class='container'><div class='col-md-12'><table class='table table-striped' style='width:100%'>";
        echo '<tr>';
        echo "<td width='10%'><h4>HTTP Method</h4></td>";
        echo "<td width='30%'><h4>URL</h4></td>";
        echo "<td width='30%'><h4>Route</h4></td>";
        echo "<td width='30%'><h4>Corresponding Action</h4></td>";
        echo '</tr>';

        foreach ($routeCollection as $value)
        {
            echo '<tr>';
            echo '<td>'.$value->methods()[0].'</td>';
            echo "<td><a href='".$value->uri()."' target='_blank'>".$value->uri().'</a> </td>';
            echo '<td>'.$value->getName().'</td>';
            echo '<td>'.$value->getActionName().'</td>';
            echo '</tr>';
        }

        echo '</table></div></div>';
        echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>';
    }

    return philsroutes();
});


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/sap', function () {
//     return view('partials.pages.login');
// });

// Route::get('/reg', function () {
//     return view('partials.pages.register');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'HomeController@dash')->name('dashboard');
Route::get('/sales-dashboard', 'HomeController@salesdash')->name('sales-dashboard');
Route::get('/marketing-dashboard', 'HomeController@marketingdash')->name('marketing-dashboard');
Route::get('/social-dashboard', 'HomeController@socialdash')->name('social-dashboard');
Route::get('/analytical-dashboard', 'HomeController@anadash')->name('analytical-dashboard');

Route::resource('users', 'UserController');

Route::resource('userinfos', 'UserinfoController');


Route::resource('users', 'UserController');

resources/views/layouts/app-old.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html class="no-js" data-ng-app="LCA Dashboard">
<head>
    <!-- Meta-Information -->
    <title>LCA Dashboard</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Vendor: Bootstrap 4 Stylesheets  -->
    <link rel="stylesheet" href="{!! asset('/css/jquery-ui.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('/css/bootstrap.min.css') !!}" type="text/css">

    <!-- Our Website CSS Styles -->
    <link rel="stylesheet" href="{!! asset('/css/icons.min.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('/css/main.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('/css/responsive.css') !!}" type="text/css">

    <!-- Color Scheme -->
    {{-- <link rel="stylesheet" href="{!! asset('/css/color-schemes/color.css') !!}" type="text/css" title="color3"> --}}
    {{-- <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color1.css') !!}" title="color1"> --}}
    <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color2.css') !!}" title="color2">
    {{-- <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color4.css') !!}" title="color4"> --}}
    {{-- <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color5.css') !!}" title="color5"> --}}

        <!-- Vendor: Javascripts -->
    <script src="{!! asset('/js/jquery.min.js') !!}" type="text/javascript"></script>
</head>
<body class="dark">
    @include('templates/header')
    <!-- Our Website Content Goes Here -->
    <div class="panel-data expand-data" data-ng-view>

    @yield('content')

    
    </div>
     <div style="clear:both"></div>
 
    @include('templates/footer')

    <!-- Vendor: Angular, followed by our custom Javascripts -->
    <script src="{!! asset('/js/angular.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/angular-route.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/bootstrap.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery-ui.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/select2.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/slick.min.js') !!}" type="text/javascript"></script>

    <!-- Our Website Javascripts -->
    <script src="{!! asset('/js/isotope.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/isotope-int.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.counterup.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/waypoints.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/highcharts.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/exporting.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/highcharts-more.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/moment.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.circliful.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/fullcalendar.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/skycons.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/elementQuery.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/betterweather.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.vmap.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.asia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.europe.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.australia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.africa.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.north-america.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.south-america.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.algeria.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.argentina.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.brazil.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.canada.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.croatia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.europe.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.france.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.germany.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.greece.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.indonesia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.iran.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.iraq.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.new_regions_france.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.russia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.serbia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.tunisia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.turkey.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.ukraine.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.usa.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.world.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.downCount.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.bootstrap-touchspin.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.formtowizard.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/form-validator.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/form-validator-lang-en.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/cropbox-min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.slimscroll.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/ion.rangeSlider.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.poptrox.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/styleswitcher.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/https://maps.google.com/maps/api/js?sensor=false') !!}"></script>
    <script src="{!! asset('/js/main.js') !!}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html class="no-js" data-ng-app="LCA Dashboard">
<head>
    <!-- Meta-Information -->
    <title>LCA Dashboard</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Vendor: Bootstrap 4 Stylesheets  -->
    <link rel="stylesheet" href="{!! asset('/css/jquery-ui.min.css') !!}">
    <link rel="stylesheet" href="{!! asset('/css/bootstrap.min.css') !!}" type="text/css">

    <!-- Our Website CSS Styles -->
    <link rel="stylesheet" href="{!! asset('/css/icons.min.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('/css/main.css') !!}" type="text/css">
    <link rel="stylesheet" href="{!! asset('/css/responsive.css') !!}" type="text/css">

    <!-- Color Scheme -->
    {{-- <link rel="stylesheet" href="{!! asset('/css/color-schemes/color.css') !!}" type="text/css" title="color3"> --}}
    {{-- <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color1.css') !!}" title="color1"> --}}
    <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color2.css') !!}" title="color2">
    <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color4.css') !!}" title="color4">
    <link rel="alternate stylesheet" href="{!! asset('/css/color-schemes/color5.css') !!}" title="color5">

        <!-- Vendor: Javascripts -->
    <script src="{!! asset('/js/jquery.min.js') !!}" type="text/javascript"></script>
</head>
<body class="dark">
    {{-- @include('templates/header') --}}
    <!-- Our Website Content Goes Here -->
    <div class="panel-data expand-data" data-ng-view>
    @yield('content')
    </div>
     
 
    @include('templates/footer')

    <!-- Vendor: Angular, followed by our custom Javascripts -->
    <script src="{!! asset('/js/angular.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/angular-route.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/bootstrap.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery-ui.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/select2.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/slick.min.js') !!}" type="text/javascript"></script>

    <!-- Our Website Javascripts -->
    <script src="{!! asset('/js/isotope.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/isotope-int.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.counterup.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/waypoints.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/highcharts.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/exporting.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/highcharts-more.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/moment.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.circliful.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/fullcalendar.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/skycons.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/elementQuery.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/betterweather.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.vmap.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.asia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.europe.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.australia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.africa.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.north-america.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/continents/jquery.vmap.south-america.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.algeria.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.argentina.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.brazil.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.canada.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.croatia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.europe.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.france.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.germany.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.greece.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.indonesia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.iran.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.iraq.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.new_regions_france.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.russia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.serbia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.tunisia.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.turkey.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.ukraine.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.usa.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/maps/jquery.vmap.world.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.downCount.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.bootstrap-touchspin.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.formtowizard.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/form-validator.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/form-validator-lang-en.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/cropbox-min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.slimscroll.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/ion.rangeSlider.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/jquery.poptrox.min.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/js/styleswitcher.js') !!}" type="text/javascript"></script>
    <script src="{!! asset('/https://maps.google.com/maps/api/js?sensor=false') !!}"></script>
    <script src="{!! asset('/js/main.js') !!}" type="text/javascript"></script>
</body>
</html>

resources/views/layouts/errors.blade.php
@if(count($errors))
<div class="form-group">
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
				<li>{{ $error}}</li>
			@endforeach
		</ul>
	</div>
</div>
@endif

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('users*') ? 'active' : '' }}">
    <a href="{!! route('users.index') !!}"><i class="fa fa-edit"></i><span><strong>Users</strong></span></a>
</li>

<li class="{{ Request::is('userinfos*') ? 'active' : '' }}">
    <a href="{!! route('userinfos.index') !!}"><i class="fa fa-edit"></i><span><strong>UserInfos</strong></span></a>
</li>
 